<div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
    <div>
        <div class="flex items-center gap-2 text-xs text-[#8b97aa]"><span class="size-1.5 rounded-full bg-[#5bc891]"></span><span>系統運作正常</span><span class="text-[#c4cad4]">·</span><span data-current-time>2024/10/28 09:48</span></div>
        <h1 class="mt-3 text-[28px] font-semibold tracking-[-0.035em] text-[#162137] sm:text-[32px]">早安，Yvonne <span class="inline-block">👋</span></h1>
        <p class="mt-2 text-sm text-[#78859a]">這是你今天的營運摘要，以下是目前最值得關注的數據。</p>
    </div>
    <div class="relative flex items-center gap-2">
        <button type="button" data-toast="報表已匯出，稍後將開始下載。" class="flex h-10 items-center gap-2 rounded-xl border border-[#dfe5ee] bg-white px-3.5 text-xs font-semibold text-[#53627b] transition hover:border-[#bfcce0] hover:text-[#26364f]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M10 3v9M6.5 8.5 10 12l3.5-3.5M4.5 15.5h11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>匯出報表</button>
        <button id="date-toggle" type="button" class="flex h-10 items-center gap-2 rounded-xl border border-[#dfe5ee] bg-white px-3.5 text-xs font-semibold text-[#53627b] transition hover:border-[#bfcce0] hover:text-[#26364f]" aria-expanded="false"><svg class="size-4 text-[#7b8ba6]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><rect x="3.5" y="4.5" width="13" height="12" rx="2" stroke="currentColor" stroke-width="1.5"/><path d="M6.5 3v3M13.5 3v3M3.5 8h13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/><path d="M7 11h2M11 11h2M7 14h2" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg><span id="date-label">2024 年 10 月</span><svg class="ml-1 size-3.5 text-[#8b98aa]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m5 7.5 5 5 5-5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        <div id="date-popover" class="popover-panel absolute right-0 top-12 z-20 hidden w-44 rounded-2xl border border-[#e2e7ef] bg-white p-2 shadow-[0_18px_50px_rgba(28,44,75,0.14)]"><button type="button" data-date-option="本月" class="date-option w-full rounded-xl bg-[#eff7f3] px-3 py-2.5 text-left text-xs font-semibold text-[#308d65]">2024 年 10 月</button><button type="button" data-date-option="上月" class="date-option mt-1 w-full rounded-xl px-3 py-2.5 text-left text-xs font-medium text-[#68758b] transition hover:bg-[#f6f8fb]">2024 年 09 月</button><button type="button" data-date-option="本季" class="date-option mt-1 w-full rounded-xl px-3 py-2.5 text-left text-xs font-medium text-[#68758b] transition hover:bg-[#f6f8fb]">2024 年第 3 季</button></div>
    </div>
</div>
