<article class="panel-card" id="finance">
    <div class="flex items-start justify-between"><div><h2 class="section-title">待辦事項</h2><p class="mt-1.5 text-xs text-[#8b97a9]">今天有 5 件事需要你的注意</p></div><span class="flex size-7 items-center justify-center rounded-lg bg-[#fff1ee] text-[11px] font-bold text-[#dc7869]">5</span></div>
    <div class="mt-5 space-y-1">
        <button type="button" data-toast="已開啟低庫存清單。" class="task-item group"><span class="task-icon bg-[#fff1ee] text-[#e27b6a]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M10 3.5 17 16H3l7-12.5Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="M10 8v3M10 13.5h.01" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></span><span class="min-w-0 flex-1 text-left"><span class="block text-xs font-semibold text-[#38465c]">低庫存警示</span><span class="mt-1 block truncate text-[10px] text-[#9aa5b5]">A-204 無線滑鼠僅剩 18 件</span></span><svg class="size-4 shrink-0 text-[#bbc3cf] transition group-hover:translate-x-0.5 group-hover:text-[#7185a6]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m7.5 4 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        <button type="button" data-toast="已開啟待開立發票列表。" class="task-item group"><span class="task-icon bg-[#fff6e7] text-[#d79a45]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><rect x="4" y="3.5" width="12" height="13" rx="1.8" stroke="currentColor" stroke-width="1.5"/><path d="M7 7h6M7 10h6M7 13h3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></span><span class="min-w-0 flex-1 text-left"><span class="block text-xs font-semibold text-[#38465c]">發票待開立</span><span class="mt-1 block truncate text-[10px] text-[#9aa5b5]">本週還有 3 筆銷售訂單</span></span><svg class="size-4 shrink-0 text-[#bbc3cf] transition group-hover:translate-x-0.5 group-hover:text-[#7185a6]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m7.5 4 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        <button type="button" data-toast="已開啟付款核准清單。" class="task-item group"><span class="task-icon bg-[#edf3ff] text-[#718bd1]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M4 5.5h12v9H4zM6.5 3.5v4M13.5 3.5v4M7 10h6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span class="min-w-0 flex-1 text-left"><span class="block text-xs font-semibold text-[#38465c]">付款核准</span><span class="mt-1 block truncate text-[10px] text-[#9aa5b5]">採購部有 5 筆請款待確認</span></span><svg class="size-4 shrink-0 text-[#bbc3cf] transition group-hover:translate-x-0.5 group-hover:text-[#7185a6]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m7.5 4 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
    </div>
    <div class="mt-5 border-t border-[#edf0f5] pt-5"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#a0aaba]">快速操作</p><div class="mt-3 grid grid-cols-3 gap-2"><button type="button" data-toast="新增銷售訂單功能準備中。" class="quick-action"><span class="quick-action-icon bg-[#eaf8f0] text-[#43ae79]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M10 4v12M4 10h12" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg></span><span>新增訂單</span></button><button type="button" data-toast="新增商品功能準備中。" class="quick-action"><span class="quick-action-icon bg-[#edf3ff] text-[#6f8bd2]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m10 3.5 6 3.25v6.5l-6 3.25-6-3.25v-6.5l6-3.25Z" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/><path d="M7 8.5h6M10 7v5" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg></span><span>新增商品</span></button><button type="button" data-toast="建立請款單功能準備中。" class="quick-action"><span class="quick-action-icon bg-[#fff4e7] text-[#d69643]"><svg class="size-4" viewBox="0 0 20 20" fill="none" aria-hidden="true"><rect x="4" y="3.5" width="12" height="13" rx="1.8" stroke="currentColor" stroke-width="1.5"/><path d="M7 7h6M7 10h6M7 13h3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></span><span>建立請款</span></button></div></div>
</article>
