<header class="sticky top-0 z-30 border-b border-[#e7ebf2] bg-[#f5f7fb]/90 backdrop-blur-xl">
    <div class="flex h-[72px] items-center gap-4 px-5 sm:px-7">
        <button id="sidebar-toggle" type="button" class="flex size-10 shrink-0 items-center justify-center rounded-xl border border-[#e1e6ef] bg-white text-[#53627b] transition hover:border-[#c9d3e3] hover:text-[#18243a] lg:hidden" aria-label="開啟側邊欄" aria-expanded="false"><svg class="size-5" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></button>
        <div class="hidden items-center gap-2 text-xs text-[#8490a4] sm:flex"><span>工作台</span><svg class="size-3.5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m7.5 4 6 6-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="font-medium text-[#26334a]">營運總覽</span></div>
        <div class="ml-auto flex items-center gap-2 sm:gap-3">
            <label class="relative hidden w-[220px] md:block"><span class="sr-only">搜尋</span><svg class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#98a4b7]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="8.75" cy="8.75" r="4.75" stroke="currentColor" stroke-width="1.5"/><path d="m12.25 12.25 4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg><input id="global-search" type="search" placeholder="搜尋訂單、客戶或商品" class="h-10 w-full rounded-xl border border-[#e2e7ef] bg-white pl-9 pr-3 text-xs text-[#27344b] outline-none placeholder:text-[#aab3c2] focus:border-[#9cb4d4] focus:ring-4 focus:ring-[#dce7f5]"><span class="pointer-events-none absolute right-2.5 top-1/2 hidden -translate-y-1/2 rounded-md border border-[#e5e9f0] px-1.5 py-0.5 text-[10px] font-medium text-[#a5afbd] lg:block">⌘ K</span></label>
            <button type="button" class="flex size-10 items-center justify-center rounded-xl border border-[#e1e6ef] bg-white text-[#65738a] transition hover:border-[#c9d3e3] hover:text-[#18243a] md:hidden" aria-label="搜尋"><svg class="size-[18px]" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="8.75" cy="8.75" r="4.75" stroke="currentColor" stroke-width="1.5"/><path d="m12.25 12.25 4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></button>
            <div class="relative">
                <button id="notification-toggle" type="button" class="relative flex size-10 items-center justify-center rounded-xl border border-[#e1e6ef] bg-white text-[#65738a] transition hover:border-[#c9d3e3] hover:text-[#18243a]" aria-label="查看通知" aria-expanded="false"><svg class="size-[18px]" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M18 9.5a6 6 0 0 0-12 0c0 7-2.5 7-2.5 8.5h17C20.5 16.5 18 16.5 18 9.5ZM10 21h4" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="absolute right-2 top-2 size-1.5 rounded-full bg-[#f57c68] ring-2 ring-white"></span></button>
                <div id="notification-popover" class="popover-panel absolute right-0 top-12 hidden w-[310px] overflow-hidden rounded-2xl border border-[#e2e7ef] bg-white shadow-[0_18px_50px_rgba(28,44,75,0.14)]">
                    <div class="flex items-center justify-between border-b border-[#edf0f5] px-4 py-3"><p class="text-sm font-semibold text-[#1c2940]">通知中心</p><span class="rounded-full bg-[#fff0ec] px-2 py-1 text-[10px] font-semibold text-[#e56c59]">3 則未讀</span></div>
                    <div class="divide-y divide-[#edf0f5]">
                        <button type="button" class="flex w-full gap-3 px-4 py-3 text-left transition hover:bg-[#f8fafc]"><span class="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-[#fff0ec] text-[#e56c59]"><svg class="size-3.5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M10 4v6l3.5 2" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="10" cy="10" r="6.5" stroke="currentColor" stroke-width="1.5"/></svg></span><span><span class="block text-xs font-medium text-[#2b3850]">有 3 項庫存低於安全水位</span><span class="mt-1 block text-[10px] text-[#9aa5b6]">8 分鐘前</span></span></button>
                        <button type="button" class="flex w-full gap-3 px-4 py-3 text-left transition hover:bg-[#f8fafc]"><span class="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-[#eef4ff] text-[#5480d2]"><svg class="size-3.5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M5 5.5h10v9H5zM7.5 3.5v4M12.5 3.5v4M7 10h6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span><span class="block text-xs font-medium text-[#2b3850]">月底結帳提醒已建立</span><span class="mt-1 block text-[10px] text-[#9aa5b6]">1 小時前</span></span></button>
                        <button type="button" class="flex w-full gap-3 px-4 py-3 text-left transition hover:bg-[#f8fafc]"><span class="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-[#edf9f3] text-[#3eaf78]"><svg class="size-3.5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m5.5 10 2.8 2.8 6.2-6.1" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span><span class="block text-xs font-medium text-[#2b3850]">SO-2024-0248 已完成付款</span><span class="mt-1 block text-[10px] text-[#9aa5b6]">今天 09:42</span></span></button>
                    </div>
                    <button type="button" class="w-full border-t border-[#edf0f5] px-4 py-3 text-center text-xs font-semibold text-[#5e82c2] transition hover:bg-[#f8fafc]">查看全部通知</button>
                </div>
            </div>
            <div class="hidden h-7 w-px bg-[#e1e6ef] sm:block"></div>
            <button type="button" class="flex items-center gap-2 rounded-xl py-1 pl-1 pr-2 transition hover:bg-white sm:gap-3" aria-label="開啟帳戶選單"><span class="flex size-9 items-center justify-center rounded-full bg-[#f1c7aa] text-[11px] font-bold text-[#5c342b]">YC</span><span class="hidden text-left sm:block"><span class="block text-xs font-semibold text-[#26334a]">Yvonne Chen</span><span class="mt-0.5 block text-[10px] text-[#8d99aa]">營運管理員</span></span><svg class="hidden size-3.5 text-[#8792a5] sm:block" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m5 7.5 5 5 5-5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        </div>
    </div>
</header>
