<article class="panel-card overflow-hidden" id="procurement">
    <div class="flex flex-col gap-4 px-0 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="section-title">近期交易</h2><p class="mt-1.5 text-xs text-[#8b97a9]">所有部門最近的單據與異動</p></div><button type="button" data-toast="正在開啟完整交易列表。" class="inline-flex items-center gap-1.5 text-xs font-semibold text-[#5f82c1] transition hover:text-[#3e65a8]">查看全部<svg class="size-3.5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M4 10h11M11 5l5 5-5 5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div>
    <div class="mt-5 flex items-center gap-1 overflow-x-auto border-b border-[#edf0f5]"><button type="button" data-transaction-tab="all" class="transaction-tab transaction-tab-active">全部 <span>8</span></button><button type="button" data-transaction-tab="sales" class="transaction-tab">銷售 <span>3</span></button><button type="button" data-transaction-tab="procurement" class="transaction-tab">採購 <span>2</span></button><button type="button" data-transaction-tab="finance" class="transaction-tab">財務 <span>2</span></button><button type="button" data-transaction-tab="inventory" class="transaction-tab">庫存 <span>1</span></button></div>
    <div class="mt-2 overflow-x-auto"><table class="w-full min-w-[700px] text-left"><thead><tr class="border-b border-[#edf0f5] text-[10px] font-semibold uppercase tracking-[0.08em] text-[#a0aaba]"><th class="px-2 py-3 font-semibold">單據編號</th><th class="px-2 py-3 font-semibold">類型</th><th class="px-2 py-3 font-semibold">對象 / 說明</th><th class="px-2 py-3 text-right font-semibold">金額</th><th class="px-2 py-3 text-right font-semibold">狀態</th></tr></thead><tbody id="transaction-list" class="divide-y divide-[#f0f2f6]">
        <tr class="transaction-row transition hover:bg-[#fafbfd]" data-type="sales" data-searchable="SO-2024-0248 客戶付款 昱盛科技 銷售"><td class="px-2 py-3.5"><span class="text-xs font-semibold text-[#34435b]">SO-2024-0248</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">今天 09:42</span></td><td class="px-2 py-3.5"><span class="table-type table-type-sales">銷售訂單</span></td><td class="px-2 py-3.5"><span class="block text-xs font-medium text-[#3b4960]">昱盛科技</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">客戶付款</span></td><td class="px-2 py-3.5 text-right text-xs font-semibold text-[#34435b]">NT$ 86,000</td><td class="px-2 py-3.5 text-right"><span class="status-pill status-success"><i></i>已完成</span></td></tr>
        <tr class="transaction-row transition hover:bg-[#fafbfd]" data-type="procurement" data-searchable="PO-2024-0119 採購付款 尚品工業 採購"><td class="px-2 py-3.5"><span class="text-xs font-semibold text-[#34435b]">PO-2024-0119</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">今天 09:10</span></td><td class="px-2 py-3.5"><span class="table-type table-type-procurement">採購單</span></td><td class="px-2 py-3.5"><span class="block text-xs font-medium text-[#3b4960]">尚品工業</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">採購付款</span></td><td class="px-2 py-3.5 text-right text-xs font-semibold text-[#34435b]">NT$ 142,500</td><td class="px-2 py-3.5 text-right"><span class="status-pill status-warning"><i></i>待審核</span></td></tr>
        <tr class="transaction-row transition hover:bg-[#fafbfd]" data-type="finance" data-searchable="INV-2024-0881 開立發票 青禾設計 發票 財務"><td class="px-2 py-3.5"><span class="text-xs font-semibold text-[#34435b]">INV-2024-0881</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">昨天 16:28</span></td><td class="px-2 py-3.5"><span class="table-type table-type-finance">應收發票</span></td><td class="px-2 py-3.5"><span class="block text-xs font-medium text-[#3b4960]">青禾設計</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">開立發票</span></td><td class="px-2 py-3.5 text-right text-xs font-semibold text-[#34435b]">NT$ 32,800</td><td class="px-2 py-3.5 text-right"><span class="status-pill status-info"><i></i>待付款</span></td></tr>
        <tr class="transaction-row transition hover:bg-[#fafbfd]" data-type="inventory" data-searchable="STK-2024-0720 庫存調整 台中倉 庫存"><td class="px-2 py-3.5"><span class="text-xs font-semibold text-[#34435b]">STK-2024-0720</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">昨天 14:06</span></td><td class="px-2 py-3.5"><span class="table-type table-type-inventory">庫存異動</span></td><td class="px-2 py-3.5"><span class="block text-xs font-medium text-[#3b4960]">台中倉</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">庫存調整</span></td><td class="px-2 py-3.5 text-right text-xs font-semibold text-[#34435b]">NT$ 18,400</td><td class="px-2 py-3.5 text-right"><span class="status-pill status-success"><i></i>已完成</span></td></tr>
        <tr class="transaction-row transition hover:bg-[#fafbfd]" data-type="procurement" data-searchable="PO-2024-0118 進貨驗收 宏維電子 採購"><td class="px-2 py-3.5"><span class="text-xs font-semibold text-[#34435b]">PO-2024-0118</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">昨天 11:32</span></td><td class="px-2 py-3.5"><span class="table-type table-type-procurement">採購單</span></td><td class="px-2 py-3.5"><span class="block text-xs font-medium text-[#3b4960]">宏維電子</span><span class="mt-1 block text-[10px] text-[#9ca7b6]">進貨驗收</span></td><td class="px-2 py-3.5 text-right text-xs font-semibold text-[#34435b]">NT$ 64,900</td><td class="px-2 py-3.5 text-right"><span class="status-pill status-processing"><i></i>處理中</span></td></tr>
    </tbody></table><div id="transaction-empty" class="hidden py-10 text-center text-xs text-[#9aa5b5]">找不到符合條件的交易</div></div>
</article>
